
from configuracoes import ESPESSURA,CAIXA_FALA,TELA_PC,ALTURA,ATTACKS, PERSONAGEM_TAM 
import pygame

def load_perifericos():

    imagens = {}

    fala_inicial = pygame.image.load('imagens/ct_introducao.jpg')
    imagens['fala_inicial'] = pygame.transform.scale(fala_inicial,CAIXA_FALA)
    fala_inicial2 = pygame.image.load('imagens/ct_introducao2.jpg')
    imagens['fala_inicial2'] = pygame.transform.scale(fala_inicial2,CAIXA_FALA)
    decisao = pygame.image.load('imagens/ct_assistir_anime.jpg')
    imagens['anime'] = pygame.transform.scale(decisao,CAIXA_FALA)
    decisao2 = pygame.image.load('imagens/ct_estudar_dessoft.jpg')
    imagens['estudar'] = pygame.transform.scale(decisao2,CAIXA_FALA)
    decisao3 = pygame.image.load('imagens/ct_dormir_mais.jpg')
    imagens['dormir'] = pygame.transform.scale(decisao3,CAIXA_FALA)
    pos_anime1 = pygame.image.load('imagens/ct_pos_anime_anime.png')
    imagens['pos_anime_anime'] = pygame.transform.scale(pos_anime1,CAIXA_FALA)
    pos_anime2 = pygame.image.load('imagens/ct_pos_anime_estudar_dessoft.png')
    imagens['pos_anime_estudar'] = pygame.transform.scale(pos_anime2,CAIXA_FALA)
    sad_anime =  pygame.image.load('imagens/ct_pos_anime_sad.png')
    imagens['sad_anime'] = pygame.transform.scale(sad_anime,CAIXA_FALA)
    sad_anime2 =  pygame.image.load('imagens/ct_pos_anime_sad2.png')
    imagens['sad_anime2'] = pygame.transform.scale(sad_anime2,CAIXA_FALA)
    anime_e_estudar = pygame.image.load('imagens/ct_pos_anime_estudar_estudar.jpg')
    imagens['estudar_pos_anime'] = pygame.transform.scale(anime_e_estudar,CAIXA_FALA)
    estudar = pygame.image.load('imagens/ct_pos_estudar.jpg')
    imagens['pos_estudar'] = pygame.transform.scale(estudar,CAIXA_FALA)
    ganha_proef = pygame.image.load('imagens/ct_proef.jpg')
    imagens['proficiente'] = pygame.transform.scale(ganha_proef,CAIXA_FALA)
    continua_estud_sim = pygame.image.load('imagens/ct_continuar_sim.jpg')
    imagens['continua_sim'] = pygame.transform.scale(continua_estud_sim,CAIXA_FALA)
    continua_estud_nao = pygame.image.load('imagens/ct_continuar_nao.jpg')
    imagens['continua_nao'] = pygame.transform.scale(continua_estud_nao,CAIXA_FALA)
    recomeco = pygame.image.load('imagens/ct_recomeco.jpg')
    imagens['recomeco'] = pygame.transform.scale(recomeco,CAIXA_FALA)

    final_dia = pygame.image.load('imagens/fim_dia1.jpg')
    imagens['FIM_DIA_SO_ANIME'] = pygame.transform.scale(final_dia,CAIXA_FALA)
    na_cadeira = pygame.image.load('imagens/Paola_cadeira_clear.png').convert_alpha()
    imagens['na_cadeira'] = pygame.transform.scale(na_cadeira, PERSONAGEM_TAM)
    shingeki = pygame.image.load('imagens/shingeki.jpg')
    imagens['shingeki'] = pygame.transform.scale(shingeki, TELA_PC)
    academia_python = pygame.image.load('imagens/academia_python.jpg')
    imagens['academia'] = pygame.transform.scale(academia_python, TELA_PC)
    pontos_20 = pygame.image.load('imagens/ct_20_pontos.png')
    imagens['proficiente20'] = pygame.transform.scale(pontos_20,CAIXA_FALA)
    pontos_10 = pygame.image.load('imagens/ct_10_pontos.png')
    imagens['proficiente10'] = pygame.transform.scale(pontos_10,CAIXA_FALA)
    fim_dia_anime_estudar = pygame.image.load('imagens/ct_fim_dia_anime_estudar.jpg')
    imagens['fim_dia_anime_estudar'] = pygame.transform.scale(fim_dia_anime_estudar,CAIXA_FALA)
    fim_dia_so_estudar = pygame.image.load('imagens/ct_fim_dia_so_estudo.jpg')
    imagens['fim_dia_so_estudar'] = pygame.transform.scale(fim_dia_anime_estudar,CAIXA_FALA)
    anime_nao_estudar_serie = pygame.image.load('imagens/ct_anime_nao_estudar_serie.jpg')
    imagens['anime_nao_estudar_serie'] = pygame.transform.scale(anime_nao_estudar_serie,CAIXA_FALA)
    anime_nao_estudar_dormir = pygame.image.load('imagens/ct_anime_nao_estudar_dormir.jpg')
    imagens['anime_nao_estudar_dormir'] = pygame.transform.scale(anime_nao_estudar_dormir,CAIXA_FALA)
    series = pygame.image.load('imagens/series_plat.jpg')
    imagens['series'] = pygame.transform.scale(series, TELA_PC)
    acorda_tarde = pygame.image.load('imagens/ct_acordou_tarde_serie.jpg')
    imagens['acordou_tarde_serie'] =  pygame.transform.scale(acorda_tarde, CAIXA_FALA)
    dormir_mais = pygame.image.load('imagens/ct_dormir_muito.jpg')
    imagens['dormir_muito'] = pygame.transform.scale(dormir_mais, CAIXA_FALA)
    dia2_estudar = pygame.image.load('imagens/dia2_estudar.jpg')
    imagens['dia2_estudar'] = pygame.transform.scale(dia2_estudar, CAIXA_FALA)
    dia2_dormir = pygame.image.load('imagens/dia2_dormir.jpg')
    imagens['dia2_dormir'] = pygame.transform.scale(dia2_dormir, CAIXA_FALA)
    dia2_anime = pygame.image.load('imagens/dia2_anime.jpg')
    imagens['dia2_anime'] = pygame.transform.scale(dia2_anime, CAIXA_FALA)
    estudar_serie = pygame.image.load('imagens/ct_estudar_serie.jpg')
    imagens['estudar_serie'] = pygame.transform.scale(estudar_serie, CAIXA_FALA)
    estudar_dormir = pygame.image.load('imagens/ct_estudar_dormir.jpg')
    imagens['estudar_dormir'] = pygame.transform.scale(estudar_dormir, CAIXA_FALA)
    serie_dormir = pygame.image.load('imagens/ct_serie_dormir.jpg')
    imagens['serie_dormir'] = pygame.transform.scale(serie_dormir, CAIXA_FALA)
    estudou_muito = pygame.image.load('imagens/ct_estudou_muito.jpg')
    imagens['estudou_muito'] = pygame.transform.scale(estudou_muito, CAIXA_FALA)
    dia3 = pygame.image.load('imagens/dia3_cheio.jpg')
    imagens['dia3'] = pygame.transform.scale(dia3, CAIXA_FALA)
    dia_da_prova =  pygame.image.load('imagens/Grande_dia.jpg')
    imagens['dia_da_prova'] = pygame.transform.scale(dia_da_prova, (ESPESSURA,ALTURA))

    ataque_dicionario = pygame.image.load('imagens/ct_ataque_dicionario.jpg')
    imagens['ataque_dicionario'] = pygame.transform.scale(ataque_dicionario , CAIXA_FALA)
    ataque_for = pygame.image.load('imagens/ct_ataque_for.jpg')
    imagens['ataque_for'] = pygame.transform.scale(ataque_for , CAIXA_FALA)
    ataque_input = pygame.image.load('imagens/ct_ataque_input.jpg')
    imagens['ataque_input'] = pygame.transform.scale(ataque_input , CAIXA_FALA)
    ataque_while = pygame.image.load('imagens/ct_ataque_while.jpg')
    imagens['ataque_while'] = pygame.transform.scale(ataque_while , CAIXA_FALA)
    ataque2_dicionario = pygame.image.load('imagens/ct_ataque2_dicionario.jpg')
    imagens['ataque2_dicionario'] = pygame.transform.scale(ataque2_dicionario , CAIXA_FALA)
    ataque2_ifelse = pygame.image.load('imagens/ct_ataque2_ifelse.jpg')
    imagens['ataque2_ifelse'] = pygame.transform.scale(ataque2_ifelse , CAIXA_FALA)
    ataque2_input = pygame.image.load('imagens/ct_ataque2_input.jpg')
    imagens['ataque2_input'] = pygame.transform.scale(ataque2_input , CAIXA_FALA)
    ataque2_lista = pygame.image.load('imagens/ct_ataque2_lista.jpg')
    imagens['ataque2_lista'] = pygame.transform.scale(ataque2_lista , CAIXA_FALA)
    ataque3_for = pygame.image.load('imagens/ct_ataque3_for.jpg')
    imagens['ataque3_for'] = pygame.transform.scale(ataque3_for , CAIXA_FALA)
    ataque3_ifelse = pygame.image.load('imagens/ct_ataque3_ifelse.jpg')
    imagens['ataque3_ifelse'] = pygame.transform.scale(ataque3_ifelse , CAIXA_FALA)
    ataque3_lista = pygame.image.load('imagens/ct_ataque3_lista.jpg')
    imagens['ataque3_lista'] = pygame.transform.scale(ataque3_lista , CAIXA_FALA)
    ataque3_while = pygame.image.load('imagens/ct_ataque3_while.jpg')
    imagens['ataque3_while'] = pygame.transform.scale(ataque3_while , CAIXA_FALA)

    atacar_lista = pygame.image.load('imagens/atacar_lista.jpg')
    imagens['atacar_lista'] = pygame.transform.scale(atacar_lista, ATTACKS)
    atacar_input = pygame.image.load('imagens/atacar_input.jpg')
    imagens['atacar_input'] = pygame.transform.scale(atacar_input, ATTACKS)
    atacar_for = pygame.image.load('imagens/atacar_for.jpg')
    imagens['atacar_for'] = pygame.transform.scale(atacar_for, ATTACKS)
    atacar_while = pygame.image.load('imagens/atacar_while.jpg')
    imagens['atacar_while'] = pygame.transform.scale(atacar_while, ATTACKS)
    atacar_dicionario = pygame.image.load('imagens/atacar_dicionario.jpg')
    imagens['atacar_dicionario'] =  pygame.transform.scale(atacar_dicionario, ATTACKS)
    atacar_ifelse = pygame.image.load('imagens/atacar_ifelse.jpg')
    imagens['atacar_ifelse'] = pygame.transform.scale(atacar_ifelse, ATTACKS)

    loop = pygame.image.load('imagens/ct_loop.jpg')
    imagens['loop'] = pygame.transform.scale(loop, CAIXA_FALA)
    invalido = pygame.image.load('imagens/ct_invalido.jpg')
    imagens['invalido'] = pygame.transform.scale(invalido , CAIXA_FALA)
    range_errado =pygame.image.load('imagens/ct_range.jpg')
    imagens['range_errado'] =pygame.transform.scale(range_errado , CAIXA_FALA)
    sem_condicao = pygame.image.load('imagens/ct_sem_condicao.jpg')
    imagens['sem_condicao'] =pygame.transform.scale(sem_condicao , CAIXA_FALA)
    indice_errado = pygame.image.load('imagens/ct_indice_errado.jpg')
    imagens['indice_errado'] = pygame.transform.scale(indice_errado , CAIXA_FALA)


    background = pygame.image.load('imagens/fundo_galaxia.jpg').convert()
    imagens['background'] = pygame.transform.scale(background, (ESPESSURA, ALTURA))
    ataque = pygame.image.load("imagens/ct_ATAQUE.png")
    imagens['ataque'] = pygame.transform.scale(ataque, (ESPESSURA,150))
    defesa = pygame.image.load("imagens/ct_DEFESA.png")
    imagens['defesa'] = pygame.transform.scale(defesa, (ESPESSURA,150))
    fugir = pygame.image.load("imagens/ct_DESISTIR.png")
    imagens['fugir'] = pygame.transform.scale(fugir, (ESPESSURA,150))
    toshi = pygame.image.load("imagens/toshi_clear.png")
    imagens['toshi'] = pygame.transform.scale(toshi, (150,150))
    dano = pygame.image.load("imagens/dano.png")
    imagens['dano'] =  pygame.transform.scale(dano, (ESPESSURA,170))
    personagem = pygame.image.load('imagens/Paola.png').convert_alpha()
    imagens['personagem'] = pygame.transform.scale(personagem, PERSONAGEM_TAM)
    quarto = pygame.image.load('imagens/quarto.jpg')
    imagens['quarto'] = pygame.transform.scale(quarto, (ESPESSURA, ALTURA))
    personagem_quarto = pygame.image.load('imagens/Paola2_back.png').convert_alpha()
    imagens['personagem_quarto'] = pygame.transform.scale(personagem_quarto,PERSONAGEM_TAM)
    inicial = pygame.image.load('imagens/tela_inicial.jpg')
    imagens['tela_inicial'] = pygame.transform.scale(inicial,(ESPESSURA,ALTURA))
    bad_final = pygame.image.load('imagens/ficou_dp.jpg')
    imagens['ficou_dp'] = pygame.transform.scale(bad_final,(ESPESSURA,ALTURA))
    bom_final = pygame.image.load('imagens/passamo.jpg')
    imagens['passamo'] = pygame.transform.scale(bom_final,(ESPESSURA,ALTURA))
    nao_pode = pygame.image.load('imagens/nao_pode.jpg')
    imagens['nao_pode'] = pygame.transform.scale(nao_pode , CAIXA_FALA)
    menos_estresse = pygame.image.load('imagens/diminui_estresse.jpg')
    imagens['diminui_estresse'] = pygame.transform.scale(menos_estresse , (300,150))




    up_prof15 = []
    up_prof10 = []
    up_prof20 = []


    for i in range(8):
        # Os arquivos de animação são numerados de 1 a 8
        imagem15 = 'imagens/up/mais_15_{}.png'.format(i+1)
        imagem10 = 'imagens/up/mais_10_{}.png'.format(i+1)
        imagem20 = 'imagens/up/mais_20_{}.png'.format(i+1)
        upgrade15 = pygame.image.load(imagem15).convert()
        upgrade10 = pygame.image.load(imagem10).convert()
        upgrade20 = pygame.image.load(imagem20).convert()
        upgrade10 = pygame.transform.scale(upgrade10, (32, 32))
        upgrade15 = pygame.transform.scale(upgrade15, (32, 32))
        upgrade20 = pygame.transform.scale(upgrade20, (32, 32))
        up_prof15.append(upgrade15)
        up_prof10.append(upgrade10)
        up_prof20.append(upgrade20)
        
    imagens['up_prof15'] = up_prof15
    imagens['up_prof10'] = up_prof10
    imagens['up_prof20'] = up_prof20

    return imagens

anima_ataque = pygame.image.load('imagens/binario2.png')
anima_ataque = pygame.transform.scale(anima_ataque, ATTACKS)


